### ISSUE TITLE
how exactly did you intend to be contacted on here?

### ISSUE THREAD

**Issue by jcq333** [Lymkwi/Lymkwi#1]

**Comment by Lymkwi** [comment]
That's a fair point, I forgot that GitHub still does not really have any inter-account messaging feature (and, now that I think about it, thank goodness).
Updated my profile page and profile to add an email ( 07c5ed8b797182d82fa82306537835b1069cd063 ).
If you have anything else to add onto this issue, please do. Otherwise I'll close it... whenever I remember to.

**Comment by Lymkwi** [comment]
Well, i remembered to close it, finally.
